### ISSUE TITLE
Hardening options

### ISSUE THREAD

**Issue by zqpvr** [daechir/xenos-install-kit#5]
Implement options from https://github.com/trimstray/linux-hardening-checklist#services and edit in /etc/fstab its very important there to harden /var/log /var/log/audit /tmp /boot /dev/shm /home and I tested it using lynis

**Comment by daechir** [comment]
Hi,

This installer actually already does some of the hardening you are requesting (though maybe not in the way lynis is checking for it). Unlike other security focused systems I opted to use the bind option wherever I could to greatly simplify the installation process. The only differences I can see here is that we're missing a separate /var/log, /var/log/audit and /var/tmp.
 
Unfortunately separating /var/log and /var/log/audit with defaults,bind,nosuid,noexec,nodev causes tpm2-abrmd.service to fail entirely. Additionally other features like systemctl poweroff stop working in a non-elevated context. Likewise /var/tmp/ is used solely for systemds private tmp sandboxing feature (at present) and the permissions are a hard 700. I haven't bothered making that separate because I'm certain it will cause some sort of issue.

Disregarding the major 3 differences I can see on the checklist that /boot is mounted with ro, which obviously will break mkinitcpio and bootctl. Additionally /usr is mounted with ro too, which will obviously break pacman updates. That's about all I can see from the outset. In summary this is surely something that should be addressed but will need worked out over time.

Perhaps you can provide your /etc/fstab here in a code snippet for testing or a pull request of some sort.

**Comment by daechir** [comment]
Hi,

After some testing I can verify that the system is still operating as intended with these changes (But only when using the bind option). Without using the bind option things just tend to break. This leads us to a fork in the road: 

1) We can still attempt to create different partitions for each in S1.sh and harden them in S2b.sh. 
2) We keep the bind options in place and implement as is. 

To be honest the bind option essentially does the same thing as separating the partitions (Unless my testing and understanding is off).

Here is the lower half of my edited fstab for you to test with:
```
/etc /xenos-etc none defaults,bind,nodev 0 0
/usr /xenos-usr none defaults,bind,nodev 0 0
/var /xenos-var-1 none  defaults,bind,nosuid,nodev 0 0
/var/log /xenos-var-2/log none defaults,bind,nosuid,nodev,noexec 0 0
/var/log/audit /xenos-var-3/log/audit none defaults,bind,nosuid,nodev,noexec 0 0
/var/tmp /xenos-tmp none defaults,bind,nosuid,nodev,noexec 0 0
/home /xenos-home none defaults,bind,nosuid,nodev,noexec 0 0
tmpfs /tmp tmpfs defaults,nosuid,nodev,noexec 0 0
tmpfs /dev/shm tmpfs defaults,nosuid,nodev,noexec 0 0
proc /proc proc nosuid,nodev,noexec,hidepid=2,gid=proc 0 0
``` 
Let me know what your thoughts are.

**Comment by daechir** [comment]
Note: This may not be the expected solution or even a permanent solution but it's a working one.

Summarizing this issue:
Enhance existing fstab mount points and restrictions.

Solution:
See commit [v3h1](https://github.com/daechir/xenos-install-kit/commit/471bec90f9649acef0b729064e12f45ddef3bc3a).

Verified by:
Testing within Arch.
